---
title: "A unified platform for missing values methods and workflows"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
bibliography: proposal.bib
---

_Applicants_

_Julie Josse, Ecole Polytechnique, France; julie.josse@polytechnique.edu_

_Nicholas Tierney, Monash university, Australia; nicholas.tierney@monash.edu_

## The Problem

Missing values are an unavoidable problem when working with real world
data. They occur for many reasons. For example, individuals choose not
to answer survey questions, weather measurement devices fail in wet
weather, or participants drop out of a study. Missing values are
problematic, as most statistical models and visualisation methods
require complete data. This problem is exacerbated as more data from
different sources become available, which may not have been designed to
be analysed together. Missing values are a problem, so what do we do
about it?

There are many ways deal with missing data in an analysis.
The most common approach, despite decades of research advocating
otherwise, is too toss out cases with missing values. At best, this is
inefficient; it wastes information from the partially observed cases. At
worst, it results in biased estimates, particularly when the
distributions of the missing values are systematically different than
the observed values. Fortunately, there are better alternatives to
tossing out cases [@Schafer2002; @Little2002; @VanBuuren2012,
@Carpenter2012]. Some analysts use model-based
approaches, integrating likelihoods or posterior distributions over
missing values. Some use imputation, creating single or multiple
completed datasets. Some use weighting approaches, appealing to ideas
from the design-based literature in survey sampling.

R has many more approaches for working with missing data than other statistical
software. To be exact, there are currently 274 R
packages on CRAN that mention missing data or imputation in their DESCRIPTION
files. There are imputation packages such as mice, Amelia, and mi 
[@mi; @amelia; @mi]. There are providing descriptive statistics and 
visualisations, like naniar, VIM, and MissingDataGUI [@naniar; @VIM; @Cheng2015]. 
There are still many other packages developed to handle complex, heterogenous
(categorical, quantitative, ordinal variables) data of large dimension 
multi-level data, such as missMDA, and MixedDataImpute 
[@Josse2016; @Murray2015].

There are many missing data packages in R that solve real problems. A
problem with so many options is navigating the decision paralysis of
choice - which one is right for the case at hand. It is not trivial.

This application aims to valorize current work in missing data by
providing a unified platform that lists and organizes existing packages,
articles, tutorials, documentation, and workflows for analyses with
missing data. The platform will be easy to extend, and will be well
documented, so it can easily incorporate future research in missing
values. It will also have a focus on fostering a welcoming community.

We hope that such a tool will enable R to consolidate and strengthen its
leadership position on the subject.

## The Plan

To create this platform, we wish to address the objectives in four parts.

**Part one: listing available R packages**

We will list available packages for working with missing data, with a
brief description. These can be used as a task-view on the subject, as
there is currently no task view specific to missing data, aside from
sections social sciences
([*https://cran.r-project.org/web/views/SocialSciences.html*](https://cran.r-project.org/web/views/SocialSciences.html))
and Multivariate Statistics
([*https://cran.r-project.org/web/views/Multivariate.html*](https://cran.r-project.org/web/views/Multivariate.html)).
We intend to make a call out to other package authors and research in
missing data in the R community to join this platform. One person we
intend to contact is Stefan van Buuren, whose website
[*http://www.stefvanbuuren.nl/mi/Software.html*](http://www.stefvanbuuren.nl/mi/Software.html)
is also often used as a reference.

**Part two: list articles and related works by theme**

Similar to part one with R packages, we will list articles and related
works, organising by theme. This can be rather laborious work, to ensure
robustness we will also put a call out for authors to submit their
articles or works to be reviewed for placement on the platform/website.

**Part three: Tutorials and workflows.**

In part three, we provide peer reviewed tutorials and analysis workflows
with a variety of different kinds of missing data. For example, these
could focus on exploration and visualization at different stages of the
analyses, advantages and drawbacks of methods such as likelihood based
approaches, and imputation methods. After imputation or other treatment
of the missing data, we will encourage assessing the impact on
subsequent analyses and inferences.

**Part four: future extensions and beyond**

By providing a platform and community to discuss missing data in R,
software, and approaches and workflows, we are providing a base from
which we can grow. For example, this platform could collect datasets to
benchmark imputation methods, which are currently not being done
anywhere in the world. By having a community involved in this, we can
then have useful discussion on the benchmarks, even organize events like
a challenge to provide the best imputation methods, in a similar fashion
to the M4 forecasting competition
(https://robjhyndman.com/hyndsight/m4comp/).

Other ideas that we would like to consider are describing universal
approaches to multiple imputation, other special types of missing value
(other than NA like STATAs special missing values), altering messages in
the base R to encourage other approaches than deleting missing
observations by default, or at least indicating the risks, etc.

Expected impact: Missing values handling is crucial for data analysis
and an easy to use platform could allow users to give more values to
their analyses.


## Team

[**Julie Josse**](http://juliejosse.com/) is Professor of Statistics at Ecole
Polytechnique in France. Julie was trained as an engineer in statistics in an
Agronomy University. Her PhD was given the award "Best PhD in Applied Statistics" by the French Statistical Society. She has specialized
in missing data, visualization and the nonparametric analyses of complex data
structures. Her work was rewarded by a European Union grant in 2013 to increase
her research potential and to spend a year at Stanford University. She has
published over 30 articles and written 2 books in applied statistics. Her
vocation is to push methodological innovation to bring useful application of her
research to users, in particular in bio- and food science. Julie Josse has
developed packages to transfer her works such as missMDA dedicated to missing
values. Her experience on dealing with incomplete data is recognized by the
community: she has just compiled a "Statistical Science" special issue to have a
snapshot of the state of the art, she organized the first conference on missing
value, "MissData" in 2015 and she is often invited to give lectures around the
world to share her experience. She is deeply involved in the R community and is
part of Rforwards to widen the participation of minorities in the communities.

[**Nicholas Tierney**](http://www.njtierney.com/) was trained in Psychology before changing to statistics, recently completing his PhD in statistics at the end of 2018. Nick is currently a research fellow in the department of econometrics and business statistics, and a member of the [rOpenSci](http://ropensci.org/) community, and a [software carpentary instructor trainer](https://software-carpentry.org/blog/2018/03/welcome-more-trainers.html). Nick has written two R packages that 
focus on data visualisation and approaches for exploring missing data: [visdat](http://visdat.njtierney.com/), 
and [naniar](http://naniar.njtierney.com/). He has also authored a [peer reviewed paper on model based approaches for understanding structure in missing data](http://bmjopen.bmj.com/content/5/6/e007450.full). In addition to his experience with statistics and R package development, Nick brings experience on wrangling groups of people together to build projects and comminities, having been the lead organiser for the first two Australian rOpenSci ozunconferences ( [2017](auunconf.ropensci.org) and [2018](ozunconf17.ropensci.org)), being an active member of the Statistics Society of Australia (Young Stats rep for Queensland 2013-2016, General council member for Victoria 2017-), and also having been the organisational chair for the [Bayesian Research and Applications Group](https://bragqut.wordpress.com/) and the [NUMBAT](http://numbat.space/). Nick has presented his research using R domestically and internationally.

**Research Assistant (RA)**. The RA will have strong R skills, will have experience with bookdown, blogdown, and webservices (setting up and maintaining a new domain name, basic HTML + CSS). The RA will also have research experience, and will understand how to conduct a literature review and summarise literature. It will not be critical for the RA to have experience working with missing data, but this would be a plus. The most important skills would be for the RA to have the capacity to learn about new research areas and critically reason with the literature.

We will also contact contributors to missing data, such as François Husson, Professor of Statistics at Agrocampus Ouest, France, and Stefan van Buuren, and welcome other interest.

## Project Milestones

We would like to conduct the project over the following time periods (M1 refers
to month 1):

### Milestone one: Create guidelines, infrastructure, and call for support. $2K

1. (M1-M4).  

- Find suitable research assistant to help with this project. 
- Make a call out to members of the R community interested in missing data. 
- Establish guidelines and principles to decide what is added to this new taskview, which may involve giving badges to packages, say for example if it is on CRAN, or if it has undergone a peer review for the package code. This would mean that packages with peer review or other positive flairs (on CRAN, for example), would be easier to search for and "rated higher" than others. 
- Create website infrastructure so that it is easy to navigate and to update, likely done with bookdown or blogdown. Note that the source code for this will be hosted publicly on github.

### Milestone two: list articles and related works by theme. $4k

2. (M5-M7). List, organize the packages/articles available.

- List all R packages that work with missing data
- Using criteria and guidelines from milestone one, establish high quality R packages
and provide more information about these.
- Add flairs and themes to packages
- Similar to above, but for key articles on missing data
- Key to success here is enlisting the help of the members of the community, to submit their articles or works to be reviewed for placement on the platform/website.

### Milestone three: Tutorials and workflows. $4K

3. (M8-M11). 

- Write documentation and tutorials to better reproduce existing studies and help the users with their own analyses. 
- The idea here being to suggest good practices and pipelines to analyse data with missing values, which might involve video.
- Ideally here Nick and Julie would meet face to face.

### Milestone four (future work): future extensions and beyond $20K

4. (M12-M24). 

- Invest more time in establishing peer review practices for missing data packages. To this end, we would be able to hire a part time research software engineer to assist with an "editing" role.
- Discuss and implement: 
  - collecting datasets to benchmark imputation methods,
  - organize events like a challenge to provide the best imputation methods, in a similar fashion to the M4 forecasting competition (https://robjhyndman.com/hyndsight/m4comp/).
  - more universal approaches to multiple imputation that can incorporate many different styles and workflows.
  - Organize data benchmark repository.
  - special types of missing value (other than NA like STATA/SPSS/SAS special missing values), 
  - Providing messages/warnings in base R when missing values are omitted (e.g., in `plot`, `lm` and `table`) that indicate the risk and encourage other approaches than deletion of missings.

## How ICS can help

## Funding

The following table details the cost items.

| Item                                                      | Cost      |
|:----------------------------------------------------------|-----------|
| Employ a research assistant for one year (10 hrs / week)  | Euro 7000 |
| Meeting with partners                                     | Euro 2500 |
| online materials                                          | Euro 500  |
| Total                                                     | Euro 10000|

### Employing research assistant(s)

Julie and Nick will jointly supervise a research assistant, who will help with the Milestones desribed. 

### Meeting with Partners

It will be of great benefit to for both of us to work together face to face for one week or so. In this case it would either be a trip from France to Australia, or Australia to France. We'd like to request support for helping with the long haul flight.

### Online materials

These costs will cover a domain name and server costs for us to set up an online community.

## Dissemination

The platform we create will serve as the primary dissemination of the project. We will also write blog posts for the R Consortium site, and Nick will also blog about the experience on his personal blog.

we can maybe speak about using social media, twitter, etc...
For the team, say that we are going to contact maybe van der loo, and others?

# References
